model_list:
- model_name: ollama-llama3
  litellm_params:
    api_base: "http://localhost:11434"
    model: "ollama/llama3:instruct"
    api_key: "sk-local"
- model_name: ollama-embed
  litellm_params:
    api_base: "http://localhost:11434"
    model: "ollama/nomic-embed-text"
    api_key: "sk-local"
