// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLAbFsPK6RmmQUSANbMZPnSztUOSPIoo',
    appId: '1:408970707313:web:6be07b9b2a15338be376d0',
    messagingSenderId: '408970707313',
    projectId: 'taniai-randevu-global-73429',
    authDomain: 'taniai-randevu-global-73429.firebaseapp.com',
    storageBucket: 'taniai-randevu-global-73429.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCNHjMsyb6TSX1-FFJiVjRIshVwsWTII',
    appId: '1:408970707313:android:9a0e79e45802e002e376d0',
    messagingSenderId: '408970707313',
    projectId: 'taniai-randevu-global-73429',
    storageBucket: 'taniai-randevu-global-73429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtk-XRxjjDzOg0ztvwisIBWpxwGIiwZ_8',
    appId: '1:408970707313:ios:040e1bfd366950c6e376d0',
    messagingSenderId: '408970707313',
    projectId: 'taniai-randevu-global-73429',
    storageBucket: 'taniai-randevu-global-73429.firebasestorage.app',
    iosBundleId: 'com.tanial.tanialRandevu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLAbFsPK6RmmQUSANbMZPnSztUOSPIoo',
    appId: '1:408970707313:web:2659c4ab51f8f036e376d0',
    messagingSenderId: '408970707313',
    projectId: 'taniai-randevu-global-73429',
    authDomain: 'taniai-randevu-global-73429.firebaseapp.com',
    storageBucket: 'taniai-randevu-global-73429.firebasestorage.app',
  );
}
